name: Release

on: [workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Release Pipeline
              uses: ballerina-platform/ballerina-action@swan-lake-release
              with:
                args:
                  run release
              env:
                WORKING_DIR: ./stdlib-release
                GITHUB_TOKEN: ${{ secrets.STDLIB_GITHUB_ACCESS_TOKEN }}
