name: Release

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            -   name: Ballerina Build
                uses: ballerina-platform/ballerina-action@swan-lake-release
                with:
                    args:
                        run release
